/*
 * This source file was generated by the Gradle 'init' task
 */
package team2472lib;

import edu.wpi.first.math.geometry.Pose2d;

public class AutoAim {
    AutoPose2d target;
    double deltaHight;

    public AutoAim() {}

    public AutoAim(AutoPose2d target, double deltaHight) {
        this.target = target;
        this.deltaHight = deltaHight;
    }

    public double getTargetYaw(Pose2d currentPose, AutoPose2d target, double deltaHight) {
        this.target = target;
        this.deltaHight = deltaHight;
        Pose2d translation = currentPose.relativeTo(target);
        double angle = Math.atan2(translation.getY(), translation.getX());
        return angle;
    }

    public double getTargetYaw(Pose2d currentPose) {
        return getTargetYaw(currentPose, target, deltaHight);
    }


}
