/*
 * This source file was generated by the Gradle 'init' task
 */
package team2472lib;

import edu.wpi.first.math.geometry.Pose2d;

public class AutoAim {
    public AutoAim(Pose2d target) {}
    
}
